# Generated by Django 5.2.8 on 2025-12-22 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('oportunidades', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('telefones', models.TextField(blank=True, null=True)),
                ('mapa', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=200, null=True)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ERPAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Empresa Cliente')),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('modulo_crm_ativo', models.BooleanField(default=True)),
                ('modulo_servicos_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.erpaccount')),
            ],
        ),
        migrations.CreateModel(
            name='DetalhesServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_resumida', models.CharField(max_length=255)),
                ('codigo_servico', models.CharField(blank=True, max_length=50, null=True)),
                ('tributacao', models.CharField(blank=True, choices=[('P', 'Exportação de Serviços'), ('T', 'Operação tributável / Tributado no município'), ('F', 'Tributado fora do município'), ('V', 'Tributado fora do município, Exigibilidade Suspensa'), ('N', 'Tributado fora do município, Imune'), ('B', 'Tributado fora do município, Isento'), ('X', 'Tributado no município, Exigibilidade Suspensa'), ('M', 'Tributado no município, Imune'), ('A', 'Tributado no município, Isento')], max_length=1, null=True)),
                ('codigo_nbs', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descricao_servico', models.TextField(blank=True, null=True)),
                ('impostos_retencoes', models.TextField(blank=True, null=True)),
                ('produtos_utilizados', models.TextField(blank=True, null=True)),
                ('situacao', models.CharField(default='Ativo', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servico_alterado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servico_criado', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.erpaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.company')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.erpaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='crm.company')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.erpaccount')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='crm.erpaccount'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.erpaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stage', models.CharField(choices=[('prospect', 'Prospect'), ('qualificacao', 'Qualificação'), ('apresentacao', 'Apresentação'), ('proposta', 'Proposta'), ('negociacao', 'Negociação'), ('conclusao', 'Conclusão')], default='prospect', max_length=50)),
                ('solucao', models.CharField(blank=True, max_length=50, null=True)),
                ('origem', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_conclusao', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=20, null=True)),
                ('email_enviado', models.CharField(blank=True, max_length=10, null=True)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('outras_info', models.TextField(blank=True, null=True)),
                ('envolvidos', models.TextField(blank=True, null=True)),
                ('caracteristica', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.erpaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.company')),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities_by_contact', to='crm.contact')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.erpaccount')),
            ],
        ),
        migrations.CreateModel(
            name='OportunidadeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.erpaccount')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.servico')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('ddd', models.CharField(blank=True, max_length=5, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_contato', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('consulta_credito', models.TextField(blank=True, null=True)),
                ('telefones_email', models.TextField(blank=True, null=True)),
                ('dados_bancarios', models.TextField(blank=True, null=True)),
                ('inscricoes_cnae', models.TextField(blank=True, null=True)),
                ('integracao', models.TextField(blank=True, null=True)),
                ('faturamento_credito', models.TextField(blank=True, null=True)),
                ('tags_selecionadas', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.erpaccount')),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_alteradas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.erpaccount')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.erpaccount')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='crm.erpaccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
