# Generated by Django 5.2.6 on 2025-09-29 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_company_criado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='criado_por',
        ),
    ]
