# Generated by Django 5.2.8 on 2026-01-22 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_company_criado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('funcionario', models.CharField(max_length=255)),
                ('data_faturamento', models.DateField(blank=True, null=True)),
                ('parcelas', models.CharField(max_length=50)),
                ('produtos', models.TextField(blank=True)),
                ('despesas', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('conta_corrente', models.CharField(blank=True, max_length=100)),
                ('projeto', models.CharField(blank=True, max_length=100)),
                ('origem', models.CharField(default='Manual', max_length=50)),
                ('pedido_cliente', models.CharField(blank=True, max_length=100)),
                ('contrato_venda', models.CharField(blank=True, max_length=100)),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('cidade_prestacao', models.CharField(blank=True, max_length=100)),
                ('dados_nf', models.TextField(blank=True)),
                ('codigo_obra', models.CharField(blank=True, max_length=50)),
                ('codigo_cei', models.CharField(blank=True, max_length=50)),
                ('encapsulamento', models.CharField(blank=True, max_length=50)),
                ('data_servico', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Aguardando faturamento', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServicoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='crm.ordemservico')),
            ],
        ),
    ]
