# Generated by Django 5.2.8 on 2026-01-22 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_ordemservico_ordemservicoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='aaccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.erpaccount'),
            preserve_default=False,
        ),
    ]
