# Generated by Django 5.2.8 on 2026-01-23 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_ordemservico_aaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservicoitem',
            name='aaccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.erpaccount'),
            preserve_default=False,
        ),
    ]
