# Generated by Django 5.2.8 on 2026-01-24 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_ordemservicoitem_aaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='aaccount',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='ordemservicoitem',
            old_name='aaccount',
            new_name='account',
        ),
    ]
