# Generated by Django 5.2.6 on 2025-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_documento_remove_company_anexo_companyattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyattachment',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='companyattachment',
            name='arquivo',
            field=models.FileField(upload_to='anexos'),
        ),
    ]
