# Generated by Django 5.2.8 on 2026-01-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_rename_aaccount_ordemservico_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='parcelas',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
