# Generated by Django 5.2.8 on 2026-02-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_ordemservico_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='numero_os',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
