# Generated by Django 5.2.6 on 2025-10-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_companyattachment_criado_em_and_more'),
    ]

    operations = [
    ]
