# Generated by Django 5.2.8 on 2026-02-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_ordemservico_numero_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='numero_os',
        ),
    ]
