# Generated by Django 5.2.8 on 2026-02-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_remove_ordemservico_numero_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='numero_os',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
