# Generated by Django 5.2.6 on 2025-10-07 18:37

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_opportunity_vendedor'),  # substitua pelo nome da última migration que existe
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='vendedor',
            field=models.ForeignKey(
                to='auth.User',   # ou outro modelo de usuário que você queira referenciar
                on_delete=models.SET_NULL,
                null=True,
                blank=True,
            ),
        ),
    ]
