# Generated by Django 5.2.8 on 2026-02-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_ordemservico_numero_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='atividade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='hora',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
