# Generated by Django 5.2.6 on 2025-10-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_add_vendedor_to_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='value',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='fase',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='valor_previsao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
