# Generated by Django 5.2.6 on 2025-10-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_remove_opportunity_stage_remove_opportunity_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='valor_previsao',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('prospect', 'Prospecção'), ('proposal', 'Proposta Enviada'), ('won', 'Ganha'), ('lost', 'Perdida')], default='prospect', max_length=50),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities_by_contact', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
