# Generated by Django 5.2.6 on 2025-10-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_opportunity_fase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('qualificacao', 'Qualificação'), ('apresentacao', 'Apresentação'), ('proposta', 'Proposta'), ('negociacao', 'Negociação'), ('conclusao', 'Conclusão')], default='prospect', max_length=50),
        ),
    ]
